### ISSUE TITLE
[Suggestion] Prettifying the site

### ISSUE THREAD

**Issue by DishankJ** [Paperback-iOS/Tachiyomi-To-Paperbackup-Converter#2]
The site could be made more beautiful by slight UI changes here and there like inserting the paperback logo, etc.. I know enough CSS to do it but I can hardly understand the overall code lol. Probably with a little help I could do this and I'd be happy to contribute, Conrad.

**Comment by ConradWeiser** [comment]
The current interface was something that I've thrown up in just a few minutes to get the functionality done. A proper, more pretty version of it is being implemented in the website by Lemon. Please check out the link below for the more 'official' look to it. (It's not on the website yet, but is planned to be!)

[](https://deploy-preview-65--paperbackios.netlify.app/tools/backup-converter/)

If you have any suggestions to clean up this UI, feel free to give your input!

**Comment by DishankJ** [comment]
It already looks so good, I don't have words to describe it haha

**Comment by ConradWeiser** [comment]
System went live a while ago on our website, closing this issue!
